import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import CurrencyConverter from '../components/converter'
import Dropdown from '../components/dropdown'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.heading}>Currency Converter</div>
      <CurrencyConverter />
    </div>
  )
}
